<div id="DataTables_Table_3_wrapper" class="dataTables_wrapper dt-bootstrap5">
    <div class="row">
        <div class="col-sm-12 col-md-10"></div>
        <div class="col-sm-12 col-md-2">
            <!--<a href="https://crm1.cloudtechtiq.com/Employee/Leads/add" class="btn btn-primary waves-effect waves-light">Add Leads</a>-->
        </div>
        <div class="col-sm-12 col-md-3">
            <div class="dataTables_length" id="DataTables_Table_3_length">
                <label>
                    <select name="months" class="form-select month-selector" id="months">
                        <option value="01">January</option>
                        <option value="02">February</option>
                        <option value="03">March</option>
                        <option value="04">April</option>
                        <option value="05">May</option>
                        <option value="06">June</option>
                        <option value="07">July</option>
                        <option value="08">August</option>
                        <option value="09">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
                    </select>
                    <select name="year" class="form-select year-selector" id="year"></select>
                </label>
            </div>
        </div>




        <div class="col-sm-12 col-md-5 d-flex " style="align-self:center;">

            <form>
              <div class="input-group input-daterange" id="bs-datepicker-daterange">
                  <input type="date" id="dateRangePicker" placeholder="MM/DD/YYYY" class="form-control fromDate" name="from" value="{{request()->get('from')}}" >
                  <span class="input-group-text">to</span>
                  <input type="date" placeholder="MM/DD/YYYY" class="form-control toDate" name="to" value="{{request()->get('to')}}">
                  <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
              </div>
          </form>
      </div>
      <div class="col-sm-12 col-md-4 d-flex justify-content-center justify-content-md-end">

        <div id="DataTables_Table_3_filter" class="dataTables_filter">
            <form method="GET" action="{{ url('Employee/Leads/home') }}">
                <label>Search:
                    <input type="search" value="{{ $searchTerm }}" class="form-control" name="search" placeholder="" aria-controls="DataTables_Table_3">
                </label>
            </form>
        </div>
    </div>
</div>
</div>

<table class="dt-responsive table dataTable dtr-column" id="DataTables_Table_3" aria-describedby="DataTables_Table_3_info">
   <thead>
    <tr>
        <th class="control sorting_disabled dtr-hidden sorting_asc" rowspan="1" colspan="1" style="width: 27.6562px; display: none;" aria-label=""></th>
        <th>Lead ID</th>
        <th>CLIENT NAME</th>
        <th>MOBILE NUMBER</th>
        <th>REQUIREMENT</th>
        <th>ASSIGNED TO</th>
        <th>GENERATED BY</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
</thead>
<tbody id="result">
    @if(count($users) > 0)
    @foreach($users as $key=> $user)
    @php $leadStatus = DB::table('lead_statuses')->where('id',$user->status)->first();  @endphp
    <tr class="odd">
      <td>{{ $user->id }} </td>
      <td>
        {{$user->first_name }}
    </td>
    <td>@if($user && $user->phone_number) {{ $user->phone_number }} @endif</td>
    <td>
        @if($user && $user->requirement)
        {{ substr(strip_tags($user->requirement), 0, 10) }}
        @else
        --
        @endif
    </td>

    <td>

        @foreach($Employee as $Emp)
        @if($user && $user->assignedto == $Emp->id)
        <img class="rounded-circle" style="margin-right: 15px;" src="{{isset($Emp->profile_img) ? $Emp->profile_img : url('public/images/21104.png')}}" height="30" width="30" alt="User avatar" />{{$Emp->first_name }}<div style="font-size:12px;margin-left: 46px;margin-top: -11px;">{{$Emp->post_name}}</div>
        @endif
        @endforeach
    </td>


    <td>
        @if($user && $user->first_name)
        <img class="rounded-circle"
        style="margin-right: 15px;" 
        src="{{$user->profile_img}}"
        height="30"
        width="30"
        alt="User avatar" />{{$user->generated_by_first_name }}<div style="font-size:12px;margin-left: 46px;margin-top: -11px;">{{$user->post_name}}</div>
    @endif</td>
    <td>
        <div style="display:flex;align-items:center;">
            <div class="status" style="background-color:{{$user->leadStatusColor}};width:13px;height:13px;border-radius:50%;">&nbsp;</div>
            <span style="padding: 5px;border-radius: 4px;">{{ucfirst($leadStatus->lead_status)}}</span>
        </div>
    </td>

    <td>                     @if(in_array('Leads', array_column($RoleAccess, 'per_name')))

      <div class="d-flex">
        @if($RoleAccess[array_search('Leads', array_column($RoleAccess, 'per_name'))]['view'] == 1 || $RoleAccess[array_search('Leads', array_column($RoleAccess, 'per_name'))]['view'] == 2)

        <a href="{{url('Employee/Leads/view/'.$user->id)}}"><svg style="margin-left: 10px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" font-size="1.375rem" class="iconify iconify--tabler" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"><circle cx="12" cy="12" r="2"></circle><path d="M22 12c-2.667 4.667-6 7-10 7s-7.333-2.333-10-7c2.667-4.667 6-7 10-7s7.333 2.333 10 7"></path></g></svg></a>

        @endif
        @if($RoleAccess[array_search('Leads', array_column($RoleAccess, 'per_name'))]['delete'] == 1)

        <a href="{{ url('Employee/Leads/delete/'.$user->id) }}" id="{{ $user->id }}" class="delete_debtcase">
            <svg style="margin-left: 10px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" font-size="1.375rem" class="iconify iconify--tabler" width="1em" height="1em" viewBox="0 0 24 24">
                <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 7h16m-10 4v6m4-6v6M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-12M9 7V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3"></path>
            </svg>
        </a>
        @endif

        <a href="{{url('Employee/Quotes/add/?id='.$user->id)}}">
            <svg style="margin-left: 10px; fill: #7367f0;" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path d="M9.983 3v7.391c0 5.704-3.731 9.57-8.983 10.609l-.995-2.151c2.432-.917 3.995-3.638 3.995-5.849h-4v-10h9.983zm14.017 0v7.391c0 5.704-3.748 9.571-9 10.609l-.996-2.151c2.433-.917 3.996-3.638 3.996-5.849h-3.983v-10h9.983z"/></svg>
        </a>
    </div>
    @endif

</td>
</tr>
@endforeach
@else
<tr>
  <td class="text-center" colspan="8">No Data Found</td>
</tr>
@endif             

</tbody>
</table>
<script>

document.querySelectorAll('.year-selector').forEach(select => {
    // Populate year options dynamically if needed
   var  yearSelect = select;
    var currentYear = new Date().getFullYear();
    for (let year = currentYear - 10; year <= currentYear + 10; year++) {
        var option = document.createElement('option');
        option.value = year;
        option.text = year;
        yearSelect.appendChild(option);
    }
    // Set the current year as the selected option
    select.value = currentYear;
});
</script>

<script>

    $(document).ready(function () {
        var currentYear = new Date().getFullYear();
        var startYear = 2015;
        var $selectYear = $('#year');
        var $selectMonth = $('#months');

    // Populate the select elements with options
        for (var year = currentYear; year >= startYear; year--) {
            $selectYear.append($('<option>', {
              value: year,
              text: year
          }));
        }

        $selectYear.on('change', fetchData);
        $selectMonth.on('change', fetchData);

        function fetchData() {
            var selectedYear = $selectYear.val();
            var selectedMonth = $selectMonth.val();

            $.ajax({
              url: "{{ url('Employee/Leads/get_leads_yeardata') }}",
              method: 'GET',
              data: { year: selectedYear, month: selectedMonth },
              success: function (data) {
                // Handle the successful response
                $('#result').empty(); // Clear previous content

                if (data.length > 0) {
                  $('#result').html(data);
              } else {
                  $('#result').html('<tr><td colspan="8" class="text-center"><span>No Data Found</span></td></tr>');
              }
          },
          error: function () {
            $('#result').html('<tr><td colspan="8" class="text-center"><span>Error fetching data.</span></td></tr>');
        }
    });
        }
    });
</script>