@extends('layouts.admin')
@section('title', 'Quotes')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    @if(Session::has('success'))
   <div class="alert alert-success" role="alert">{{ Session::get('success') }}</div>
    @endif
    <div class="alert alert-success" role="alert" id="ResMsg" style="display:none;"></div>
   <!-- Users List Table -->
  <div class="card">
    <div class="row">
      <div class="col-md-6">
          <h5 class="card-header">Quote's List</h5>
      </div>
                                  @if(Auth::user()->status == 4)
            <script>
              $(document).ready(function(){
                // alert('Your are not allowed to perform this action. first complete your profile');
                var id = {{Auth::user()->id}};
                $.ajax({
        url: "{{url('user/MyProfile/edit')}}",
        method: 'GET',
        data: { id: id },
        success: function (data) {
            if (data && typeof data == 'string') {
                $('#showedit').html(data);
                $('#showedit').modal('show');
            } else {
                $('#showedit').html('<div>No Data Found</div>');
                $('#showedit').modal('show');
            }
        },
        error: function () {
            $('#showedit .modal-content').html('<div>Error fetching data.</div>');
            $('#showedit').modal('show');
        }
    });
              });
            </script>
              @endif

    </div>
      <div class="card-datatable table-responsive">
        <div id="DataTables_Table_3_wrapper" class="dataTables_wrapper dt-bootstrap5">
          <table class="dt-responsive table dataTable dtr-column" id="DataTables_Table_3" aria-describedby="DataTables_Table_3_info">
            <thead>
              <tr>
                <th class="control sorting_disabled dtr-hidden sorting_asc" rowspan="1" colspan="1" style="width: 27.6562px; display: none;" aria-label=""></th>
                <th>ID</th>
                <!-- <th>CUSTOMER NAME</th> -->
                <th>SUBJECT</th>
                <th>TOTAL AMOUNT</th>
                <th>VALID UNTIL</th>
                <th>LAST MODIFICATION</th>
                <th>Generated By</th>
                <th>Action</th>
              </tr>
            </thead>
           <tbody>
    @if(count($Quotes) > 0)
        @foreach($Quotes as $key=> $user)
            @php 
                $generated_by =  \App\Models\User::select('users.first_name','users.profile_img','company_logins.company_name')
                                    ->leftjoin('employee_details','employee_details.user_id','users.id')
                                    ->leftjoin('company_logins','company_logins.id','employee_details.company_id')
                                    ->where('users.id',$user->quotesuser_id)
                                    ->first();
            @endphp
            <tr class="odd">
                <td>{{ $key+1 }} </td>
                <td>@if($user && $user->subject) {{ $user->subject }} @endif</td>
                <td>@if($user && $user->total) {{ $user->total }} @endif</td>
                <td>@if($user && $user->valid_until) {{ date('d-m-Y', strtotime($user->valid_until)) }} @endif</td>
                <td>@if($user && $user->updated_at) {{ date('d-m-Y', strtotime($user->updated_at)) }} @endif</td>
                <td>
                    @if($generated_by && $generated_by->company_name)
                        <img class="rounded-circle" style="margin-right: 15px;margin-top: 10px;" src="{{$generated_by->profile_img}}" height="30" width="30" alt="User avatar" />@if($generated_by && $generated_by->first_name) {{ $generated_by->first_name }} @endif
                    @endif
                    <div style="font-size:12px;margin-left: 46px;margin-top: -11px;">
                        @if($generated_by && $generated_by->company_name)
                            {{$generated_by->company_name}}
                        @endif
                    </div>
                </td>
                <td>
                    @if($user && $user->status == '5')
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-icon rounded-pill dropdown-toggle hide-arrow waves-effect waves-light" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="ti ti-dots-vertical"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end" style="">
                                <li><a class="dropdown-item" href="{{url('user/Quotes/downloadPDF/'.$user->id)}}">Download PDF</a></li>
                                <li><a class="dropdown-item" href="{{url('user/Quotes/printView/'.$user->id)}}">View PDF</a></li>
                                <li><a class="dropdown-item" href="{{url('user/Quotes/view/'.$user->id)}}">View</a></li>
                            </ul>
                        </div>
                    @else
                        @if($user && $user->status == '1')
                            <select class="form-control" onchange="QuoteStatuts(value,{{$user->id}})">
                                <option @if($user && $user->status == '1') selected @endif value="1">Pending</option>
                                <option @if($user && $user->status == '2') selected @endif value="2">Decline</option>
                                <option @if($user && $user->status == '3') selected @endif value="3">Accepted</option>
                            </select>
                        @else
                            @switch($user->status)
                                @case('2')
                                    <span class="badge bg-label-warning">Decline</span>
                                    @break
                                @case('3')
                                    <span class="badge bg-label-primary">Accepted</span>
                                    @break
                                @default
                                    <span></span>
                            @endswitch
                        @endif
                    @endif
                </td>
            </tr>
        @endforeach
    @else
        <tr>
            <td class="text-center" colspan="8">No Data Found</td>
        </tr>
    @endif
</tbody>

        </table>
          <div class="p-1" style="float: right;">
          </div>
      </div>
      </div>
    </div>
</div>
@if(Auth::user()->status == 4)
<div class="modal fade show" id="showedit" data-bs-backdrop="static" tabindex="-1" aria-modal="true" role="dialog" style="display: block;">
</div>
@endif
<script type="text/javascript">
  function QuoteStatuts(value, Qid) {
    // Get the CSRF token from the meta tag in your HTML
    var csrfToken = $('meta[name="csrf-token"]').attr('content');

    $.ajax({
        url: "{{ url('user/Quotes/StatuPdate') }}",
        method: 'post',
        data: {
            value: value,
            Qid: Qid,
            _token: csrfToken
        },
        success: function (response) {
            if (response.success == true) {
                $('#ResMsg').show().html(response.message);

                // Hide #ResMsg after 3 seconds
                setTimeout(function () {
                    $('#ResMsg').hide(500);

                    // Reload the page after 3 seconds
                    setTimeout(function () {
                        location.reload();
                    }, 1000);
                }, 1000);
            }
        },
        error: function () {
            alert("Oops! Some technical error occurred.");
        }
    });
  }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.10.5/sweetalert2.min.js" integrity="sha512-WHVh4oxWZQOEVkGECWGFO41WavMMW5vNCi55lyuzDBID+dHg2PIxVufsguM7nfTYN3CEeQ/6NB46FWemzpoI6Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
  $(window).load(function(){
   swal({
  title: "Are you sure?",
  text: "You will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonClass: "btn-danger",
  confirmButtonText: "Yes, delete it!",
  cancelButtonText: "No, cancel plx!",
  closeOnConfirm: false,
  closeOnCancel: false
},
function(isConfirm) {
  if (isConfirm) {
    swal("Deleted!", "Your imaginary file has been deleted.", "success");
  } else {
    swal("Cancelled", "Your imaginary file is safe :)", "error");
  }
});
  });


</script>

@endsection